// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InitMessage {
    #[prost(string, tag = "1")]
    pub db_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub temp_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StrMessage {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OptStrMessage {
    #[prost(string, optional, tag = "1")]
    pub value: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BoolMessage {
    #[prost(bool, tag = "1")]
    pub value: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Settings {
    #[prost(bool, optional, tag = "1")]
    pub test: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FfiResult {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, optional, tag = "2")]
    pub error_message: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(oneof = "ffi_result::Data", tags = "3, 4")]
    pub data: ::core::option::Option<ffi_result::Data>,
}
/// Nested message and enum types in `FFIResult`.
pub mod ffi_result {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "3")]
        BoolMessage(super::BoolMessage),
        #[prost(message, tag = "4")]
        Settings(super::Settings),
    }
}
// @@protoc_insertion_point(module)
