// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Test {
    #[prost(bool, tag = "1")]
    pub something: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FfiResult {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, optional, tag = "2")]
    pub error_message: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(oneof = "ffi_result::Data", tags = "3")]
    pub data: ::core::option::Option<ffi_result::Data>,
}
/// Nested message and enum types in `FFIResult`.
pub mod ffi_result {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "3")]
        Test(super::Test),
    }
}
// @@protoc_insertion_point(module)
